name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test